# Generated by Django 4.0.4 on 2022-06-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='description',
            field=models.CharField(default='exit', max_length=150),
            preserve_default=False,
        ),
    ]
