# Generated by Django 4.0.4 on 2022-06-05 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0002_rename_job_title_jobs_job_title_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companyprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('services', models.CharField(max_length=120)),
                ('logo', models.ImageField(null=True, upload_to='companyprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
