# Generated by Django 4.0.4 on 2022-06-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('applicant', 'job')},
        ),
    ]
